### ISSUE TITLE
Remove "Please help us customize your experience" popup

### ISSUE THREAD

**Issue by ChiefArug** [aaronldickman/nobloatfandom#2]
![image](https://github.com/aaronldickman/nobloatfandom/assets/73862885/ac5945c6-7afe-463f-935c-c4941287e971)
More bloat, there is no reason a wiki needs to know this. It pops up after spending ~1 min on a page.

I've found just deleting the element using inspect element works fine, but I'm not familiar enough with extensions to PR that.

**Comment by aaronldickman** [comment]
1) Are you logged in when you see this?

2) Can you link a page that you're seeing this on? I've seen some fandom wikis have elements that others don't. In a fresh browser I'm not seeing this on any of the wikis I use to test.

**Comment by ChiefArug** [comment]
1. No
2. The Minecraft wiki, namely this page https://minecraft.fandom.com/wiki/Custom_world_preset though I have seen it on other MC wiki pages.

**Comment by aaronldickman** [comment]
Reproduced.

Looking at it... I'm not sure if this is bloat, or even strictly tracking related. Looks like clicking it sets a cookie with `{over18: bool}` on it. I think odds are its bloat (based on the phrasing of the popup), but just in case this is compliance-related I don't want to touch it. 

Looks after you make a decision it doesn't trigger afterwards so I'd recommend just doing that. Run a separate extension like uBlock Origin or Ghostery if you're worried about the tracking. If you're blocking first-party cookies I believe uBlock Origin has a way to blacklist elements which could be another solution to this problem.
